---@module "lazy"
---@type LazySpec
return {
  "nvim-treesitter/nvim-treesitter-textobjects",
  branch = "main",
  init = function()
    vim.g.no_plugin_maps = true
  end,
  config = function()
    -- Select
    vim.keymap.set({ "x", "o" }, "af", function()
      require("nvim-treesitter-textobjects.select").select_textobject("@function.outer", "textobjects")
    end)
    vim.keymap.set({ "x", "o" }, "if", function()
      require("nvim-treesitter-textobjects.select").select_textobject("@function.inner", "textobjects")
    end)
    vim.keymap.set({ "x", "o" }, "acl", function()
      require("nvim-treesitter-textobjects.select").select_textobject("@class.outer", "textobjects")
    end)
    vim.keymap.set({ "x", "o" }, "icl", function()
      require("nvim-treesitter-textobjects.select").select_textobject("@class.inner", "textobjects")
    end)
    vim.keymap.set({ "x", "o" }, "aco", function()
      require("nvim-treesitter-textobjects.select").select_textobject("@conditional.outer", "textobjects")
    end)
    vim.keymap.set({ "x", "o" }, "ico", function()
      require("nvim-treesitter-textobjects.select").select_textobject("@conditional.inner", "textobjects")
    end)
    vim.keymap.set({ "x", "o" }, "al", function()
      require("nvim-treesitter-textobjects.select").select_textobject("@loop.outer", "textobjects")
    end)
    vim.keymap.set({ "x", "o" }, "il", function()
      require("nvim-treesitter-textobjects.select").select_textobject("@loop.inner", "textobjects")
    end)
    vim.keymap.set({ "x", "o" }, "aa", function()
      require("nvim-treesitter-textobjects.select").select_textobject("@parameter.outer", "textobjects")
    end)
    vim.keymap.set({ "x", "o" }, "ia", function()
      require("nvim-treesitter-textobjects.select").select_textobject("@parameter.inner", "textobjects")
    end)

    -- Goto next
    vim.keymap.set({ "n", "x", "o" }, "]af", function()
      require("nvim-treesitter-textobjects.move").goto_next_start("@function.outer", "textobjects")
    end)
    vim.keymap.set({ "n", "x", "o" }, "]if", function()
      require("nvim-treesitter-textobjects.move").goto_next_start("@function.inner", "textobjects")
    end)
    vim.keymap.set({ "n", "x", "o" }, "]acl", function()
      require("nvim-treesitter-textobjects.move").goto_next_start("@class.outer", "textobjects")
    end)
    vim.keymap.set({ "n", "x", "o" }, "]icl", function()
      require("nvim-treesitter-textobjects.move").goto_next_start("@class.inner", "textobjects")
    end)
    vim.keymap.set({ "n", "x", "o" }, "]aco", function()
      require("nvim-treesitter-textobjects.move").goto_next_start("@conditional.outer", "textobjects")
    end)
    vim.keymap.set({ "n", "x", "o" }, "]ico", function()
      require("nvim-treesitter-textobjects.move").goto_next_start("@conditional.inner", "textobjects")
    end)
    vim.keymap.set({ "n", "x", "o" }, "]al", function()
      require("nvim-treesitter-textobjects.move").goto_next_start("@loop.outer", "textobjects")
    end)
    vim.keymap.set({ "n", "x", "o" }, "]il", function()
      require("nvim-treesitter-textobjects.move").goto_next_start("@loop.inner", "textobjects")
    end)
    vim.keymap.set({ "n", "x", "o" }, "]aa", function()
      require("nvim-treesitter-textobjects.move").goto_next_start("@parameter.outer", "textobjects")
    end)
    vim.keymap.set({ "n", "x", "o" }, "]ia", function()
      require("nvim-treesitter-textobjects.move").goto_next_start("@parameter.inner", "textobjects")
    end)

    -- Goto prev
    vim.keymap.set({ "n", "x", "o" }, "[af", function()
      require("nvim-treesitter-textobjects.move").goto_previous_start("@function.outer", "textobjects")
    end)
    vim.keymap.set({ "n", "x", "o" }, "[if", function()
      require("nvim-treesitter-textobjects.move").goto_previous_start("@function.inner", "textobjects")
    end)
    vim.keymap.set({ "n", "x", "o" }, "[acl", function()
      require("nvim-treesitter-textobjects.move").goto_previous_start("@class.outer", "textobjects")
    end)
    vim.keymap.set({ "n", "x", "o" }, "[icl", function()
      require("nvim-treesitter-textobjects.move").goto_previous_start("@class.inner", "textobjects")
    end)
    vim.keymap.set({ "n", "x", "o" }, "[aco", function()
      require("nvim-treesitter-textobjects.move").goto_previous_start("@conditional.outer", "textobjects")
    end)
    vim.keymap.set({ "n", "x", "o" }, "[ico", function()
      require("nvim-treesitter-textobjects.move").goto_previous_start("@conditional.inner", "textobjects")
    end)
    vim.keymap.set({ "n", "x", "o" }, "[al", function()
      require("nvim-treesitter-textobjects.move").goto_previous_start("@loop.outer", "textobjects")
    end)
    vim.keymap.set({ "n", "x", "o" }, "[il", function()
      require("nvim-treesitter-textobjects.move").goto_previous_start("@loop.inner", "textobjects")
    end)
    vim.keymap.set({ "n", "x", "o" }, "[aa", function()
      require("nvim-treesitter-textobjects.move").goto_previous_start("@parameter.outer", "textobjects")
    end)
    vim.keymap.set({ "n", "x", "o" }, "[ia", function()
      require("nvim-treesitter-textobjects.move").goto_previous_start("@parameter.inner", "textobjects")
    end)
  end,
}
