local M = {
  -- stylua: ignore
  kind = {
    Text          = " ",
    Method        = " ",
    Function      = "󰡱 ",
    Constructor   = " ",
    Field         = " ",
    Variable      = " ",
    Class         = " ",
    Interface     = " ",
    Module        = " ",
    Property      = " ",
    Unit          = "󰊱 ",
    Value         = " ",
    Enum          = " ",
    Keyword       = " ",
    Snippet       = " ",
    Color         = " ",
    File          = " ",
    Reference     = " ",
    Folder        = " ",
    EnumMember    = " ",
    Constant      = " ",
    Struct        = " ",
    Event         = " ",
    Operator      = " ",
    TypeParameter = " ",
  },
  -- stylua: ignore
  type = {
    Boolean = " ",
    Number  = "󰎠 ",
    String  = "󰅳 ",
    Array   = "󰅨 ",
    Object  = " ",
  },
  -- stylua: ignore
  other_symbols = {
    Namespace = " ",
    Package   = " ",
    Key       = " ",
    Null      = "󰟢 ",
  },
  -- stylua: ignore
  diagnostics = {
    filled = {
      Error       = "",
      Warning     = "",
      Information = "",
      Question    = "",
      Hint        = "󰌵",
    },
    outlined = {
      Error       = "",
      Warning     = "",
      Information = "",
      Question    = "",
      Hint        = "",
    }
  },
  -- stylua: ignore
  documents = {
    File            = "",
    Files           = "",
    Symlink         = "",
    Folder          = "",
    FolderOpen      = "",
    EmptyFolder     = "",
    EmptyFolderOpen = "",
    SymlinkFolder   = "",
  },
  -- stylua: ignore
  git = {
    Add       = "",
    Staged    = "",
    Mod       = "",
    Remove    = "",
    Unmerged  = "",
    Untracked = "U",
    Ignore    = "",
    Rename    = "",
    Diff      = "",
    Repo      = "",
    Octoface  = "",
  },
  debugger = {
    BreakPoint = "●",
    BreakPointConditional = "",
    BreakPointLog = "",
    BreakPointActive = "",
    BreakPointRejected = "",
    UI = "",
  },
  -- stylua: ignore
  ui = {
    GrepString    = "󱎸",
    ArrowClosed   = "",
    ArrowOpen     = "",
    Lock          = "",
    Circle        = "●",
    BigCircle     = "",
    Buffer        = "",
    Out           = "",
    NewFile       = "",
    FindFile      = "󰈞",
    RecentFile    = "󱋡",
    Lightbulb     = "",
    Project       = "",
    Dashboard     = "",
    Clock1        = "",
    Clock2        = "",
    Clock3        = "",
    Comment       = "",
    Bug           = "",
    Code          = "",
    GoTo          = "",
    HighPriority  = "󰘃",
    LSP           = "󰿘",
    Telescope     = "",
    Gear          = "",
    Path          = "",
    Refresh       = "",
    Socket        = "",
    List          = "",
    SignIn        = "",
    SignOut       = "",
    Label         = "",
    LabelOutline  = "",
    Fire          = "",
    BookMark      = "",
    Pencil2       = "✎",
    ChevronRight  = "",
    Table         = "",
    Terminal      = "",
    ToolBox       = "󰦬",
    TODO          = "",
    Calendar      = "",
    CloudDownload = "",
    Database      = "",
    Latex         = "",
    CmdStart      = "",
    SearchDown    = " ",
    SearchUp      = " ",
    Help          = " ",
    Input         = "󰥻 ",
    Scissor       = "󰩫 ",
  },
  -- stylua: ignore
  misc = {
    Tabnine  = "󰫈 ",
    Luasnip  = "󰩫",
    Squirrel = "",
    Tag      = "",
    Watch    = "",
    LazyDev  = "󰒲 "
  },
}

return M
